### PR TITLE
Updating feature/3DPBL

### PR DESCRIPTION
**Pull request by twjuliano**
The purpose of the PR is to update the `a2e-mmc/WRF` `feature/3DPBL` branch with new 3DPBL developments.

### CODE REVIEW

**Comment by ewquon** [comment]
Would these changes cause us to diverge from the 3DPBL implementation in WRF v4.3? Should we pull that in first?

**Comment by twjuliano** [comment]
@ewquon My personal fork has 3DPBL merged on top of the latest `wrf-model/WRF/develop` updates in `develop_3dpbl_on_top`. I keep that branch up to date so that it is can be easily merged into the official version once 3DPBL is ready for public release. Whether or not we should pull the newest WRF developments into this feature branch, I will leave it up to you and @phawbeck . However, at present, this merge pulls in all of the latest 3DPBL developments -- the only advantage of doing what you suggest is to have a newer version of `wrf-model/WRF/develop` updates. Thanks.

**Comment by ewquon** [comment]
@twjuliano So what's the difference between `develop_3dpbl_on_top` and `update_feature/3DPBL` being pulled in here? I think I'm missing something, because one of these branches and/or anticipated PRs seems redundant.

**Comment by twjuliano** [comment]
@ewquon Sorry for the confusion. The difference is that `develop_3dpbl_on_top` has all of the current `wrf-model/WRF/develop` commits and no `a2e-mmc/WRF` developments, while `update_feature/3DPBL` has `wrf-model/WRF/develop` commits through 29 March and current `a2e-mmc/WRF` developments. Does that make sense?

**Comment by ewquon** [comment]
Got it, @twjuliano. Do we have a small test case we can run for both versions of WRF?

**Comment by twjuliano** [comment]
@ewquon Do you mean compare output from `develop_3dpbl_on_top` with output from `update_feature/3DPBL` using a baseline LES case or something similar?

**Comment by ewquon** [comment]
> @ewquon Do you mean compare output from `develop_3dpbl_on_top` with output from `update_feature/3DPBL` using a baseline LES case or something similar?

Right. Not just for verification here, but I think it could be a useful exercise for us as WRF continues to evolve. It'd be nice to  include that in https://github.com/a2e-mmc/WRF-setups as an example.

**Comment by twjuliano** [comment]
@ewquon That makes sense, and it's a good idea. I'm just using the out-of-the-box `em_les` free convective setup. Here are some results after 1hr integration time... `develop_3dpbl_on_top` on the left and `update_feature/3DPBL` on the right.

Vertical velocity at k = 1:
image

Zonal wind component at k = 1:
image

Potential temp perturbation at k = 1:
image

While there are differences, it looks like the model is performing very similarly between the two versions. Hopefully this is sufficient for what you were thinking. Thanks.

**Pull request merged**
